[package]
name = "smml"
version = "0.1.0"
authors = ["Robert Węcławski <r.weclawski@gmail.com>"]
edition = "2018"

[dependencies]
vulkano = "0.11.1"
vulkano-shaders = "0.11"
vulkano-win = "0.11"
log = "0.4.6"
winit = "0.18"
nalgebra-glm = "0.2.0"