[package]
name = "ketch-engine"
version = "0.1.0"
authors = ["Robert Węcławski <r.weclawski@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.6"
fps_counter = "1.0.0"
structopt = "0.2.14"
ketch-editor = { path = "../ketch-editor" }
ketch-core = { path = "../ketch-core" }